export type OrderStatus = "cancelled" | "completed" | "confirmed";

// Orders table
export type OrderRow = {
  id: string;
  user_id: string | null;
  total_price: number;
  status: OrderStatus;
  created_at: string;
  discount_amount: number | null;
  voucher_id: string | null;
  payment_method: string | null;
  receiver_name: string | null;
  receiver_phone: string | null;
  shipping_address: string | null;
  cancel_reason: string | null;
};

// Order_items table
export type OrderItemRow = {
  id: string;
  order_id: string;
  product_id: string;
  product_name: string | null;
  product_image: string | null;
  size: string | null;
  quantity: number;
  base_price: number;
  topping_total: number;
  total_price: number;
  toppings: unknown;
  created_at: string;
  note: string | null;
  sugar_level: string | null;
  ice_level: string | null;
};

// Products table
export type ProductRow = {
  id: string;
  category_id: string | null;
  name: string;
  stats: string | null;
  price: number;
  sale_price: number | null;
  image: string | null;
  created_at: string;
  is_best_seller: boolean;
  is_active: boolean;
  stock_quantity: number;
  measure_value: number | null;
  measure_unit: string | null;
};

// News table
export type NewsRow = {
  id: string;
  title: string;
  description: string | null;
  content: string | null;
  image: string | null;
  is_active: boolean | null;
  created_at: string | null;
  type: string;
  hashtag: string | null;
}

// Dashboard KPI metrics
export type DashboardKpis = {
  totalOrders: number;
  revenue: number;
  confirmedOrders: number;
  lowStockProducts: number;
};

// Minimal order info for Recent Orders on Dashboard
// Pick<> utility type is used to select specific fields from OrderRow
export type DashboardRecentOrder = Pick<OrderRow, "id" | "created_at" | "total_price" | "status">;

// Top selling products for Dashboard
export type DashboardTopProduct = {
  product_id: string;
  product_name: string;
  product_image: string | null;
  sold_quantity: number;
  revenue: number;
};

export type DashboardTopSellingProduct = {
  product_id: string;
  product_name: string;
  product_image: string | null;
  sold_quantity: number;
  revenue: number; // total revenue generated by this product
};

export type InventoryTransactionType = "IN" | "OUT";

export type InventoryTransactionRow = {
  id: string;
  product_id: string;
  type: InventoryTransactionType;
  requested_quantity: number;
  applied_quantity: number;
  delta: number;
  note: string | null;
  created_by: string | null;
  created_at: string;
  input_value: number | null;
  input_unit: string | null;
  receipt_id: string | null;
};

export type DashboardInventorySummary = {
  totalIn: number;
  totalOut: number;
};

export type DashboardRecentInventoryTransaction = Pick<
  InventoryTransactionRow,
  "id" | "created_at" | "type" | "product_id" | "applied_quantity" | "delta" | "note"
> & {
  product_name: string | null; // joined from products table
};


export type DashboardLatestNewsItem = Pick<
  NewsRow,
  "id" | "title" | "description" | "image" | "created_at" | "type" | "is_active"
>;

export type RevenueChartPoint = {
  bucket: string;
  revenue: number;
};

export type OrdersCountChartPoint = {
  bucket: string;
  total: number;
  completed: number;
  confirmed: number;
  cancelled: number;
};

export type InventoryInOutChartPoint = {
  bucket: string;
  total_in: number;
  total_out: number;
};
